name: PHP Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    name: PHP Coding Standards Fixer
    steps:
      - uses: actions/checkout@v2
  
      - name: OSKAR-PHP-CS-Fixer
        uses: OskarStark/php-cs-fixer-ga@2.16.4
